// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MbReader is an autogenerated mock type for the MbReader type
type MbReader struct {
	mock.Mock
}

// ReadHolding provides a mock function with given fields: address, quantity
func (_m *MbReader) ReadHolding(address uint16, quantity uint16) ([]byte, error) {
	ret := _m.Called(address, quantity)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(uint16, uint16) []byte); ok {
		r0 = rf(address, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint16, uint16) error); ok {
		r1 = rf(address, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
